version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  groups:
    dev-dependencies:
      dependency-type: "development"
      patterns: ["*"]
      update-types: ["patch", "minor"]
    prod-dependencies:
      dependency-type: "production"
      patterns: ["*"]
      update-types: ["patch", "minor"]
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: googleapis
    versions:
    - 68.0.0
    - 70.0.0
    - 71.0.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.12
    - 7.13.8
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.1
    - 5.12.2
    - 5.12.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
  - dependency-name: query-string
    versions:
    - 7.0.0
  - dependency-name: nanoid
    versions:
    - 3.1.22
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.13.13
  - dependency-name: codemirror
    versions:
    - 5.59.3
    - 5.60.0
  - dependency-name: classnames
    versions:
    - 2.3.0
  - dependency-name: marked
    versions:
    - 1.2.8
