module.exports = [
	'Astral Rite of Acne',
	'Create Acne',
	'Cursed Ramen Erruption',
	'Dark Chant of the Dentists',
	'Erruption of Immaturity',
	'Flaming Disc of Inconvenience',
	'Heal Bad Hygene',
	'Heavenly Transfiguration of the Cream Devil',
	'Hellish Cage of Mucus',
	'Irritate Peanut Butter Fairy',
	'Luminous Erruption of Tea',
	'Mystic Spell of the Poser',
	'Sorcerous Enchantment of the Chimneysweep',
	'Steak Sauce Ray',
	'Talk to Groupie',
	'Astonishing Chant of Chocolate',
	'Astounding Pasta Puddle',
	'Ball of Annoyance',
	'Cage of Yarn',
	'Control Noodles Elemental',
	'Create Nervousness',
	'Cure Baldness',
	'Cursed Ritual of Bad Hair',
	'Dispell Piles in Dentist',
	'Eliminate Florists',
	'Illusionary Transfiguration of the Babysitter',
	'Necromantic Armor of Salad Dressing',
	'Occult Transfiguration of Foot Fetish',
	'Protection from Mucus Giant',
	'Tinsel Blast',
	'Alchemical Evocation of the Goths',
	'Call Fangirl',
	'Divine Spell of Crossdressing',
	'Dominate Ramen Giant',
	'Eliminate Vindictiveness in Gym Teacher',
	'Extra-Planar Spell of Irritation',
	'Induce Whining in Babysitter',
	'Invoke Complaining',
	'Magical Enchantment of Arrogance',
	'Occult Globe of Salad Dressing',
	'Overwhelming Enchantment of the Chocolate Fairy',
	'Sorcerous Dandruff Globe',
	'Spiritual Invocation of the Costumers',
	'Ultimate Rite of the Confetti Angel',
	'Ultimate Ritual of Mouthwash',
];