contact_links:
  - name: /r/Homebrewery Subreddit
    url: https://www.reddit.com/r/homebrewery
    about: The Homebrewery community on Reddit!
  - name: Discord of Many Things
    url: https://discord.gg/domt
    about: "Join the conversation in the #formatting channel on DoMT!"