name: General Issue
description: Report an issue unrelated to Saving
body:
  - type: markdown
    attributes:
      value: Please include as much information as possible.
  - type: checkboxes
    id: renderer
    attributes:
      label: Renderer
      description: Which renderer does this issue occur on?  If you are unsure, you can check the renderer in the Properties Editor (click the "i" in the Snippet Menu bar above the editor).
      options:
        - label: Legacy
        - label: v3
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser were you using when the issue occurred?
      options:
        - label: Chrome
        - label: Firefox
        - label: Edge
        - label: Safari
        - label: other
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which OS were you using when the issue occurred?
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: other
    validations:
      required: true
  - type: textarea
    id: user-description
    attributes:
      label: "What happened?"
      description: Please include any steps you took leading up to the issue and if you can reproduce it.  Let us know what you expected to happen, and what did happen.
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code
      description: Paste in any relevant code snippet below.
      render: gfm