const _ = require('lodash');

module.exports = function(){
	return ['<div class="card back" style="--card-width: 67mm; --card-height: 89mm;">',
	'# Magic Item',
	'## Wondrous Item, Very Rare',
	'1D10 Angry DM damage',
	'',
	'  <img src=\'https://i.imgur.com/iNJH8j9.png\'></img>',
	'',
	'  <span class="caption">Would you believe that a wizard did it?</span>',
	'  <div class="statblock">',
	'    **Effect:** The targeted player takes 1D10 *annoying-the-DM-in-a-dramatic-moment* damage. This damage cannot be mitigated in any way.',
	'  </div><br />',
	'  <div class="description centered">',
	'      *"Don\'t say it, don\'t... You said it."*',
	'  </div>',
	'</div>',
	'',
	'<br />',
	'',
	'<div class="card" style="--card-width: 67mm; --card-height: 89mm;">',
	'  # Schrodinger\'s Flying Daggers',
	'  ## Wondrous Item, Extremely OP',
	'  1D4+2 / (*Sleight of Hand bonus*)D4 when thrown',
	'',
	'  <img src=\'https://i.imgur.com/osuNuge.png\'></img>',
	'  <span class="caption">"Did I throw one dagger? Or two? Or seven? And at whom were they thrown? Or did I even throw a dagger at all?" -- Ernst Schrödinger, Last Meister of the Rogue\'s Guild</span>',
	'',
	'  <div class="statblock">',
	'    This extremely rare blade grants **+2** to both attack and damage rolls.  ',
	'    When thrown, the dagger loses this bonus, but splits into up to *Sleight of Hand bonus* 1D4 daggers, each of which may have a different target. Once the daggers stop moving, they return to a single dagger.  ',
	'    **Attunement:** When attuned, the dagger may be recalled as a free action.',
	'  </div>',
	'</div>',
	].join('\n');
};