module.exports = {
  "Abi-Dalzim's Horrid Wilting": {
    "athigherlevel": "",
    "description": "(a bit of sponge)\r\nYou draw the moisture from every creature in a 30-foot cube centered on a point you choose within range. Each creature in that area must make a Constitution saving throw. Constructs and undead aren't affected, and plants and water elementals make this saving throw with disadvantage. A creature takes 10d8 necrotic damage on a failed save, or half as much damage on a successful one.",
    "source": "Elemental Evil",
    "level": "8",
    "range": "150 feet",
    "casting_time": "1 Action",
    "id": "406",
    "slug": "abi-dalzims-horrid-wilting",
    "scag": "0",
    "page": "15",
    "components": "V, S, M",
    "ritual": "No",
    "name": "Abi-Dalzim's Horrid Wilting",
    "school": "Necromancy",
    "ee": "1",
    "classes": [
      "Sorcerer",
      "Wizard"
    ],
    "duration": "Instantaneous",
    "concentration": "No"
  },
  "Absorb Elements ": {
    "athigherlevel": " When you cast this spell using a spell slot of 2nd level or higher, the extra damage increases by 1d6 for each slot level above 1st.",
    "description": "1 Reaction, which you take when you take acid, cold, fire, lightning, or thunder damage\n\nThe spell captures some of the incoming energy, lessening its effect on you and storing it for your next melee attack. You have resistance to the triggering damage type until the start of your next turn. Also, the first time you hit with a melee attack on your next turn, the target takes an extra 1d6 damage of the triggering type, and the spell ends.\r\n",
    "source": "Elemental Evil",
    "level": "1",
    "range": "Self",
    "casting_time": "Special",
    "id": "377",
    "slug": "absorb-elements",
    "scag": "0",
    "page": "15",
    "components": "S",
    "ritual": "No",
    "name": "Absorb Elements ",
    "school": "Abjuration",
    "ee": "1",
    "classes": [
      "Druid",
      "Ranger",
      "Wizard"
    ],
    "duration": "1 round",
    "concentration": "No"
  },
  "Acid Splash": {
    "athigherlevel": "This spell's damage increases by 1d6 when you reach 5th level (2d6), 11th level (3d6), and 17th level (4d6).",
    "description": "You hurl a bubble of acid. \nChoose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage. \n\n",
    "source": "Player's Handbook",
    "level": "0",
    "range": "60 feet",
    "casting_time": "1 Action",
    "id": "1",
    "slug": "acid-splash",
    "scag": "0",
    "page": "211",
    "components": "V, S",
    "ritual": "No",
    "name": "Acid Splash",
    "school": "Conjuration",
    "ee": "0",
    "classes": [
      "Sorcerer",
      "Wizard"
    ],
    "duration": "Instantaneous",
    "concentration": "No"
  },
  "Aganazzar's Scorcher": {
    "athigherlevel": " When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.",
    "description": "A line of roaring flame 30 feet long and 5 feet wide emanates from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 3d8 fire damage on a failed save, or half as much damage on a successful one.\r\n",
    "source": "Elemental Evil",
    "level": "2",
    "range": "30 feet",
    "casting_time": "1 Action",
    "id": "399",
    "slug": "aganazzars-scorcher",
    "scag": "0",
    "page": "15",
    "components": "V, S, M",
    "ritual": "No",
    "name": "Aganazzar's Scorcher",
    "school": "Evocation",
    "ee": "1",
    "classes": [
      "Sorcerer",
      "Wizard"
    ],
    "duration": "Instantaneous",
    "concentration": "No"
  },
  "Aid": {
    "athigherlevel": "When you cast this spell using a spell slot of 3rd level or higher, a target's hit points increase by an additional 5 for each slot level above 2nd.",
    "description": "Your spell bolsters your allies with toughness and resolve. \nChoose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration.",
    "source": "Player's Handbook",
    "level": "2",
    "range": "30 feet",
    "casting_time": "1 Action",
    "id": "2",
    "slug": "aid",
    "scag": "0",
    "page": "211",
    "components": "V, S, M (a tiny strip of white cloth)",
    "ritual": "No",
    "name": "Aid",
    "school": "Abjuration",
    "ee": "0",
    "classes": [
      "Cleric",
      "Paladin"
    ],
    "duration": "8 hours",
    "concentration": "No"
  },
  "Alarm (Ritual)": {
    "athigherlevel": "",
    "description": "You set an alarm against unwanted intrusion. \r\nChoose a door, a window, or an area within range that is no larger than a 20-foot cube. Until the spell ends, an alarm alerts you whenever a tiny or larger creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is mental or audible. \n\nA mental alarm alerts you with a ping in your mind if you are within 1 mile of the warded area. This ping awakens you if you are sleeping. \r\nAn audible alarm produces the sound of a hand bell for 10 seconds within 60 feet.",
    "source": "Player's Handbook",
    "level": "1",
    "range": "30 feet",
    "casting_time": "1 Minute",
    "id": "3",
    "slug": "alarm-ritual",
    "scag": "0",
    "page": "211",
    "components": "V, S, M (a tiny bell and a piece of fine silver wire)",
    "ritual": "Yes",
    "name": "Alarm (Ritual)",
    "school": "Abjuration",
    "ee": "0",
    "classes": [
      "Ranger",
      "Wizard"
    ],
    "duration": "8 hours",
    "concentration": "No"
  },
  "Alter Self": {
    "athigherlevel": "",
    "description": "You assume a different form.\r\nWhen you cast the spell, choose one of the following options, the effects of which last for the duration of the spell. While the spell lasts, you can end one option as an action to gain the benefits of a different one.\r\n\r\nAquatic Adaptation. You adapt your body to an aquatic environment, sprouting gills, and growing webbing between your fingers. You can breathe underwater and gain a swimming speed equal to your walking speed.\r\n\r\nChange Appearance. You transform your appearnce. You decide what you look like, including your height, weight, facial features, sound of your voice, hair length, coloration, and distinguishing characteristics, if any. \r\nYou can make yourself appear as a member of another race, though none of your statistics change. You also don't appear as a creature of a different size than you, and your basic shape stays the same; if you're bipedal, you can't use this spell to become quadrupedal, for instance. At any time for the duration of the spell, you can use your action to change your appearance in this way again.\r\n\n&nbsp;Natural Weapons. You grow claws, fangs, spines,&nbsp;horns, or a different natural weapon of your choice. Your unarmed strikes deal 1d6 bludgeoning, piercing, or slashing damage, as appropriate to the natural weapon you chose, and you are proficient with your unarmed strikes. Finally, the natural weapon is magic and you have a +1 bonus to the attack and damage rolls you make using it.",
    "source": "Player's Handbook",
    "level": "2",
    "range": "Self",
    "casting_time": "1 Action",
    "id": "4",
    "slug": "alter-self",
    "scag": "0",
    "page": "211",
    "components": "V, S",
    "ritual": "No",
    "name": "Alter Self",
    "school": "Transmutation",
    "ee": "0",
    "classes": [
      "Sorcerer",
      "Wizard"
    ],
    "duration": "Concentration, up to 1 hour",
    "concentration": "Yes"
  },
}