export default [
	// ############################## Systems
	// D&D
	"system:D&D Original",
	"system:D&D Basic",
	"system:AD&D 1e",
	"system:AD&D 2e",
	"system:D&D 3e",
	"system:D&D 3.5e",
	"system:D&D 4e",
	"system:D&D 5e",
	"system:D&D 5e 2024",
	"system:BD&D (B/X)",
	"system:D&D Essentials",

	// Other Famous RPGs
	"system:Pathfinder 1e",
	"system:Pathfinder 2e",
	"system:Vampire: The Masquerade",
	"system:Werewolf: The Apocalypse",
	"system:Mage: The Ascension",
	"system:Call of Cthulhu",
	"system:Shadowrun",
	"system:Star Wars RPG (D6/D20/Edge of the Empire)",
	"system:Warhammer Fantasy Roleplay",
	"system:Cyberpunk 2020",
	"system:Blades in the Dark",
	"system:Daggerheart",
	"system:Draw Steel",
	"system:Mutants and Masterminds",

	// Meta
	"meta:V3",
	"meta:Legacy",
	"meta:Template",
	"meta:Theme",
	"meta:free",
	"meta:Character Sheet",
	"meta:Documentation",
	"meta:NPC",
	"meta:Guide",
	"meta:Resource",
	"meta:Notes",
	"meta:Example",

	// Book type
	"type:Campaign",
	"type:Campaign Setting",
	"type:Adventure",
	"type:One-Shot",
	"type:Setting",
	"type:World",
	"type:Lore",
	"type:History",
	"type:Dungeon Master",
	"type:Encounter Pack",
	"type:Encounter",
	"type:Session Notes",
	"type:reference",
	"type:Handbook",
	"type:Manual",
	"type:Manuals",
	"type:Compendium",
	"type:Bestiary",

	// ###################################### RPG Keywords

	// Classes / Subclasses / Archetypes
	"Class",
	"Subclass",
	"Archetype",
	"Martial",
	"Half-Caster",
	"Full Caster",
	"Artificer",
	"Barbarian",
	"Bard",
	"Cleric",
	"Druid",
	"Fighter",
	"Monk",
	"Paladin",
	"Rogue",
	"Sorcerer",
	"Warlock",
	"Wizard",

	// Races / Species / Lineages
	"Race",
	"Ancestry",
	"Lineage",
	"Aasimar",
	"Beastfolk",
	"Dragonborn",
	"Dwarf",
	"Elf",
	"Goblin",
	"Half-Elf",
	"Half-Orc",
	"Human",
	"Kobold",
	"Lizardfolk",
	"Lycan",
	"Orc",
	"Tiefling",
	"Vampire",
	"Yuan-Ti",

	// Magic / Spells / Items
	"Magic",
	"Magic Item",
	"Magic Items",
	"Wondrous Item",
	"Magic Weapon",
	"Artifact",
	"Spell",
	"Spells",
	"Cantrip",
	"Cantrips",
	"Eldritch",
	"Eldritch Invocation",
	"Invocation",
	"Invocations",
	"Pact boon",
	"Pact Boon",
	"Spellcaster",
	"Spellblade",
	"Magical Tattoos",
	"Enchantment",
	"Enchanted",
	"Attunement",
	"Requires Attunement",
	"Rune",
	"Runes",
	"Wand",
	"Rod",
	"Scroll",
	"Potion",
	"Potions",
	"Item",
	"Items",
	"Bag of Holding",

	// Monsters / Creatures / Enemies
	"Monster",
	"Creatures",
	"Creature",
	"Beast",
	"Beasts",
	"Humanoid",
	"Undead",
	"Fiend",
	"Aberration",
	"Ooze",
	"Giant",
	"Dragon",
	"Monstrosity",
	"Demon",
	"Devil",
	"Elemental",
	"Construct",
	"Constructs",
	"Boss",
	"BBEG",

	// ############################# Media / Pop Culture
	"One Piece",
	"Dragon Ball",
	"Dragon Ball Z",
	"Naruto",
	"Jujutsu Kaisen",
	"Fairy Tail",
	"Final Fantasy",
	"Kingdom Hearts",
	"Elder Scrolls",
	"Skyrim",
	"WoW",
	"World of Warcraft",
	"Marvel Comics",
	"DC Comics",
	"Pokemon",
	"League of Legends",
	"Runeterra",
	"Arcane",
	"Yu-Gi-Oh",
	"Minecraft",
	"Don't Starve",
	"Witcher",
	"Witcher 3",
	"Cyberpunk",
	"Cyberpunk 2077",
	"Fallout",
	"Divinity Original Sin 2",
	"Fullmetal Alchemist",
	"Fullmetal Alchemist Brotherhood",
	"Lobotomy Corporation",
	"Bloodborne",
	"Dragonlance",
	"Shackled City Adventure Path",
	"Baldurs Gate 3",
	"Library of Ruina",
	"Radiant Citadel",
	"Ravenloft",
	"Forgotten Realms",
	"Exandria",
	"Critical Role",
	"Star Wars",
	"SW5e",
	"Star Wars 5e",
];
